// Generated by gencpp from file stud_hee/MyVelocity.msg
// DO NOT EDIT!


#ifndef STUD_HEE_MESSAGE_MYVELOCITY_H
#define STUD_HEE_MESSAGE_MYVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace stud_hee
{
template <class ContainerAllocator>
struct MyVelocity_
{
  typedef MyVelocity_<ContainerAllocator> Type;

  MyVelocity_()
    : header()
    , vel()  {
      vel.assign(0.0);
  }
  MyVelocity_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vel()  {
  (void)_alloc;
      vel.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 6>  _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::stud_hee::MyVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stud_hee::MyVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct MyVelocity_

typedef ::stud_hee::MyVelocity_<std::allocator<void> > MyVelocity;

typedef boost::shared_ptr< ::stud_hee::MyVelocity > MyVelocityPtr;
typedef boost::shared_ptr< ::stud_hee::MyVelocity const> MyVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stud_hee::MyVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stud_hee::MyVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stud_hee::MyVelocity_<ContainerAllocator1> & lhs, const ::stud_hee::MyVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vel == rhs.vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stud_hee::MyVelocity_<ContainerAllocator1> & lhs, const ::stud_hee::MyVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stud_hee

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stud_hee::MyVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stud_hee::MyVelocity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stud_hee::MyVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stud_hee::MyVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stud_hee::MyVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stud_hee::MyVelocity_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stud_hee::MyVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cff194b6077cbc50b5e74ac69c88fd00";
  }

  static const char* value(const ::stud_hee::MyVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcff194b6077cbc50ULL;
  static const uint64_t static_value2 = 0xb5e74ac69c88fd00ULL;
};

template<class ContainerAllocator>
struct DataType< ::stud_hee::MyVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stud_hee/MyVelocity";
  }

  static const char* value(const ::stud_hee::MyVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stud_hee::MyVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[6] vel\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::stud_hee::MyVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stud_hee::MyVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stud_hee::MyVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stud_hee::MyVelocity_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vel[]" << std::endl;
    for (size_t i = 0; i < v.vel.size(); ++i)
    {
      s << indent << "  vel[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STUD_HEE_MESSAGE_MYVELOCITY_H
